version: "3.9"

services:
  mongodb:
    image: 'mongo:5.0'
    container_name: 'us-mongodb'
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadm
      - MONGO_INITDB_ROOT_PASSWORD=mongoadm
    volumes:
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
      - ./mongo-volume:/data/db
  user_service:
    restart: always
    image: theartofdevel/notes_system.user_service:latest
    container_name: user_service
    ports:
      - 10005:10005